import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/components/provider/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="ja">
        <body>{children}</body>
      </html>
    </SessionProvider>
  );
}
